[package]
name = "cli-gif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.12.0"
minreq = { version = "2.11.0", features = ["https"] }
